# ======================
# 🛠 General Build Settings
# ======================

[build]
  publish = "public"
  command = ""
  functions = "netlify/functions"

# ======================
# 🌎 Environment Variables
# ======================

[context.production.environment]
  NODE_ENV = "production"
  OPENAI_API_KEY = "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"
  SUPABASE_URL= "https://rjeoowxsxlckguekywek.supabase.co"
  SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZW9vd3hzeGxja2d1ZWt5d2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Mjk0MjMsImV4cCI6MjA2MzIwNTQyM30.jHs7zA1OXPlg5FxdQ9mNaSK6UNZuydYMy1CiRpXK-4o"
  HOOK_TOL_TOKEN_SECRET = "${HOOK_TOL_TOKEN_SECRET}"
  EMAIL_SERVER_API = "${EMAIL_SERVER_API}"
  NETLIFY_AUTH_TOKEN= "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRfCr30Kf63LPzGtJ6b5SIbNvxFO63owpJVbf/vIIg4MN8kWbmEsLpYorzVZxzvU/C2Jgj6WajRPgsxbH1ZNq6pVMnLUpvw9VJ4FncKdED2s78hXmO0cyxAVdFNfKWPPE0vA2hv50gjDWKx9WUqXJlfJdI1Uas3Pb+sW6rFFgauu91LtJmdNe1GCXQFuz3jxe1I3Dpi7Y6LZI8cMpXPPG4VpdQbW4M1kACnyVVb17wBg7/KD1XcJJG3PpRexuNVQUVQZ7WCyUps/tn4zvmvPfSyuTQBVCqrCYgQzqo+blkcSAHHDzE0iTk4k6FKgQ2rf+Sn5Y4ScO57dMI0L2weZnFlWpHORORc1ITIvBSY442pnyhkcGgZzKV6KFmPu/Ub2f47vA20mMrnqLyRhISmOrb8WjUdhHGYF4kgdzlOMpaLHo5YU5uChXMmIkrLdJNDl0U73Cp4LoE2ReA2r2NFhbUw7AEwhQ10B9mW9/aU6ANZ4IoUXpEcHFFYxp5hKtj0o/XIvmztRVzP7lHQ9wB6vGj11oQQkb2qy+Rk/yLLU4VIZJp41Wi6PJXgTk1Q8Toy7X30t/n/bqqA0021VEtO0pB/cMUx5vPFJ0ReDaRrLcpgtNruJCPqhRboTCsFxfxw/QatIVoLfIHax0xx1w5/7l4gOo+KblN4uKP3FNxErX/bw=="
  NETLIFY_SITE_ID= "https://hooktravel.netlify.app"

# ======================
# 🌐 Redirects & Rewrites
# ======================

[[redirects]]
  from = "/api/*"
  to = "https://api.hooktravel.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ======================
# 🔐 Security Headers
# ======================

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# ======================
# 🧪 Staging Environment
# ======================

[context.staging.environment]
  NODE_ENV = "staging"
  SUPABASE_URL = "${STAGING_SUPABASE_URL}"
